name: hello

on:
  push:
    branches:
      - shigwata/dagger

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: hello
        uses: dagger/dagger-for-github@v3
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2.16
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            project init
            project update
            do hello
